# superparameters
batch_size: 4
epoch: 10
num_workers: 4
valid_size: 0.15
shuffle: True # 是否将训练集打乱
input_size: 572
pin_memory: True
initial_lr: 0.001
n_iter: 1

# path
image_path: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Img
label_path: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Label
save_folder: D:\project\Unet-lite\myUnet\exp

