# superparameters
batch_size: 4
epoch: 10
num_workers: 0
valid_size: 0.15
shuffle: True
input_size: 572
pin_memory: True
initial_lr: 0.001
n_iter: 1

print_every: 1

# win path

#image_path: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Img
#label_path: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Label
#
#save_folder: D:\project\Unet-lite\myUnet\exp
#test_image: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Img\
#
#test_label: D:\project\ISNet-master\IRSTD-1k\IRSTD1k_Label

# linux path

image_path: /home/youtian/Documents/pro/pyCode/MLF-IRDet/data/dataset/IRSTD-1k/images
label_path: /home/youtian/Documents/pro/pyCode/MLF-IRDet/data/dataset/IRSTD-1k/masks

save_folder: /home/youtian/Documents/pro/pyCode/Unet-lite/myUnet/exp
test_image: ...

test_label: ...