# structure
encode:
  # [chanel, kernel_size, stride, padding, sample]
  - [[3, 64, 64], 3, 1, 0, True]
  - [[64, 128, 128], 3, 1, 0, True]
  - [[128, 256, 256], 3, 1, 0, True]
  - [[256, 512, 512], 3, 1, 0, True]

decode:
  - [[512, 1024, 512], 3, 1, 0, False]
  - [[1024, 512, 256], 3, 1, 0, False]
  - [[512, 256, 128], 3, 1, 0, False]
  - [[256, 128, 64], 3, 1, 0, False]

out:
  - [[128, 64], 3, 1, 0]
  - [[64, 64], 3, 1, 0]
  - [[64, 2], 1, 1, 0]